### ISSUE TITLE
new design bugs

### ISSUE THREAD

**Issue by eknuth** [Ecotrust/solomon#166]
# From Scott

Swap out hamburger with 'house'
Missing the registration fields 
Selecting option in Single Select doesn't grey out the 'Other' option
Next arrow not highlighting when ready 
Bottom depth allowed me to advance before choosing units
Not able to see the species in the accordion (because of color)

**Comment by sfletche** [comment]
Additional issues 

Map at the bottom of screen is offset 

When I log in the screen has no indication that I am waiting for the next page to load 

Similar issue when clicking New Report for the first time – it hung so long I figured it was broken

Can the buttons be bigger, or can they provide some indication that they were pressed?
accordion species list is difficult to read (groups can be read easily but the actual species can not) 

Was not able to click/select 4th question on ‘fish-released’ page under fish traps (was not able to scroll any more) – had to click ‘done’ then click 4th question field in order to enter text

Total Trip Pounds should be moved (to same page as grid question…?)

After answering last question I was presented with a blank screen – had to advance again to return to home screen – no indication that the survey had been completed (or what to do next – e.g. how to submit survey)

**Comment by sfletche** [comment]
need to create separate tickets for each of these (after another review)

**Comment by sfletche** [comment]
closing this as individual tickets have been created for each issue
