### ISSUE TITLE
Time is off in the dashboard

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#191]
So the respondant times I see in the admin list view is correct but the dashboard respondant time doesn't match this and is incorrect.  It seems to be ahead 11 hours?  They should match!

**Comment by eknuth** [comment]
Ok.  Timezone stuff is always a challenge.

First of all, I was using the wrong formatting string and was outputting month instead of minute.

Second there seems to be some weird interaction between the time zones coming out of the date base and the date formatting.  The date looks is stored as Solomons UTC+11 in the db and seems to be correct.  It was getting rewritten into the local time of the browser, which is opaque, but not so bad.

But there seemed to be a problem with the math.  I created a new date filter that is a light wrapper around the date.js formatter.  It's doing the date math correctly, but will show the time converted into the browsers local time...

We might need to think about the database timezone.

**Comment by twelch** [comment]
Thanks, sounds like we should get dialed on our pattern for this as it will come up in every project

**Comment by twelch** [comment]
Is this updated on production?  I'm still seeing the times as different. see screenshots

![screen shot 2013-10-13 at 1 16 11 am](https://f.cloud.github.com/assets/81816/1319811/d06b3fec-3316-11e3-9c74-ecf7dface30d.png)
![screen shot 2013-10-13 at 1 16 03 am](https://f.cloud.github.com/assets/81816/1319812/d4f7cbfc-3316-11e3-97e1-f8cc8a75eef3.png)
