### ISSUE TITLE
fix piece/heap cost count questions

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#232]

**Comment by twelch** [comment]
I can't seem to crack this nut, although I did a similar question for the shellfish surveys.

I have a fish family multiple choice question # 35.
I feed these answers into grid question # 37, what prices are each family being sold (multiple choice grid column).
I then feed this into grid question # 38, how many pieces/heaps for sale at each price for each family.

For question # 38, each row should be a family and price combination.  So if I select the family 'Balistidae (triggerfishes)' and the prices 20, 30, and 50.  # 38 should have three rows:
Balistidae (triggerfishes) - 20
Balistidae (triggerfishes) - 30
Balistidae (triggerfishes) - 50

I've set it up just like the shellfish question but for the life of me I can't get it to go.  The survey just skips over the question.  Hoping you can take a look tomorrow as one of the top tasks.  Hopefully I'm missing something simple.

Thanks

**Comment by eknuth** [comment]
Got it.  The condition was correct, but the options_from_previous was invalid.  You had 'family-prices:prices-sold' and it needed to be 'family-prices:prices'.

Since it couldn't find the answer it was looking for, it thought you didn't have any rows and skipped the grid.  

When we can spend some time on the authoring tool we can make those links explicit, rather than just specifying strings.  Skipping the question because it didn't have the answer isn't necessarily an incorrect behavior, but made it hard to diagnose :(

I've made the change to the survey on test and prod.
